/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.IM.gui;

import com.IM.biz.IceCream;
import com.IM.biz.IceCreamMachine;
import static com.IM.gui.Exe.IM;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaime Riesgo
 */
public class ExeGraph extends javax.swing.JFrame {
static IceCreamMachine IM = new IceCreamMachine();
static DecimalFormat df = new DecimalFormat("#0.00");
    /**
     * Creates new form ExeGraph
     */
    public ExeGraph() {
        initComponents();
        setIconImage( new ImageIcon(getClass().getResource("/img/helado.png")).getImage());
    }
private void updateTablaHelados() {
     ArrayList<IceCream> iceCreams = null;          
       
                try {
                    iceCreams = IM.showIceCreams();
                    DefaultTableModel m = (DefaultTableModel) TablaHelados.getModel();
                    m.setRowCount(0);
                   
                    
                    for (IceCream iceCream : iceCreams) {
                        Object[] o = {iceCream.getPosition(),iceCream.getName(),df.format(iceCream.getCost()),iceCream.getType(),iceCream.getQuantity()};
                        m.addRow(o);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(ExeGraph.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }
public void updatejLabelTextDinero() {
    jLabelTextDinero.setText("Dinero: "+df.format(IM.getPurse())+"€");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHelados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelElecion = new javax.swing.JLabel();
        button08 = new java.awt.Button();
        button09 = new java.awt.Button();
        button07 = new java.awt.Button();
        button04 = new java.awt.Button();
        button03 = new java.awt.Button();
        button01 = new java.awt.Button();
        button02 = new java.awt.Button();
        button05 = new java.awt.Button();
        button00 = new java.awt.Button();
        buttonBorrar = new java.awt.Button();
        buttonConfirmar = new java.awt.Button();
        button06 = new java.awt.Button();
        jLabelPosicion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTextDinero = new javax.swing.JLabel();
        Introducir_Dinero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemVentas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maquina de helados Jaime Y Sina");
        setExtendedState(MAXIMIZED_BOTH);

        TablaHelados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TablaHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio", "Tipo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaHelados.setShowGrid(true);
        TablaHelados.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaHeladosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TablaHelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaHeladosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaHelados);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelElecion.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelElecion.setText("Elección:");

        button08.setLabel("8");
        button08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button08ActionPerformed(evt);
            }
        });

        button09.setLabel("9");
        button09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button09ActionPerformed(evt);
            }
        });

        button07.setLabel("7");
        button07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button07ActionPerformed(evt);
            }
        });

        button04.setLabel("4");
        button04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button04ActionPerformed(evt);
            }
        });

        button03.setLabel("3");
        button03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button03ActionPerformed(evt);
            }
        });

        button01.setLabel("1");
        button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button01ActionPerformed(evt);
            }
        });

        button02.setLabel("2");
        button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button02ActionPerformed(evt);
            }
        });

        button05.setLabel("5");
        button05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button05ActionPerformed(evt);
            }
        });

        button00.setLabel("0");
        button00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button00ActionPerformed(evt);
            }
        });

        buttonBorrar.setLabel("X");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        buttonConfirmar.setLabel("✓");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        button06.setLabel("6");
        button06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button06ActionPerformed(evt);
            }
        });

        jLabelPosicion.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelElecion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPosicion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button07, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button08, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button04, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button05, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button09, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button06, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button01, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button00, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button02, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button03, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelElecion)
                    .addComponent(jLabelPosicion))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button09, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button08, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button07, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button04, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button05, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button06, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button01, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button02, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button03, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button00, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabelTextDinero.setBackground(new java.awt.Color(0, 204, 204));
        jLabelTextDinero.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelTextDinero.setText("Dinero: "+df.format(IM.getPurse())+"€");

        Introducir_Dinero.setText("Introducir Dinero");
        Introducir_Dinero.setToolTipText("Solo effectivo.");
        Introducir_Dinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Introducir_DineroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Introducir_Dinero)
                    .addComponent(jLabelTextDinero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Introducir_Dinero)
                .addGap(58, 58, 58)
                .addComponent(jLabelTextDinero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giphy.gif"))); // NOI18N

        jMenu2.setText("Opciones");

        jMenuItemVentas.setText("ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVentas);

        jMenuItem1.setText("Rellenar Maquina");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaHeladosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaHeladosAncestorAdded
        updateTablaHelados();
    }//GEN-LAST:event_TablaHeladosAncestorAdded

    private void button08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button08ActionPerformed
// TODO add your handling code here:
 if (jLabelPosicion.getText().length()<2) {
         jLabelPosicion.setText(jLabelPosicion.getText()+"8");
        }
        
    }//GEN-LAST:event_button08ActionPerformed

    private void button09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button09ActionPerformed
        // TODO add your handling code here:
        if (jLabelPosicion.getText().length()<2) {
         jLabelPosicion.setText(jLabelPosicion.getText()+"9");
        }
       
    }//GEN-LAST:event_button09ActionPerformed

    private void button07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button07ActionPerformed
        // TODO add your handling code here:
        if (jLabelPosicion.getText().length()<2) {
         jLabelPosicion.setText(jLabelPosicion.getText()+"7");
        }
        
    }//GEN-LAST:event_button07ActionPerformed

    private void button04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button04ActionPerformed
        // TODO add your handling code here:
        if (jLabelPosicion.getText().length()<2) {
         jLabelPosicion.setText(jLabelPosicion.getText()+"4");
        }
       
    }//GEN-LAST:event_button04ActionPerformed

    private void button03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button03ActionPerformed
        // TODO add your handling code here:
        if (jLabelPosicion.getText().length()<2) {
         jLabelPosicion.setText(jLabelPosicion.getText()+"3");
        }
         
    }//GEN-LAST:event_button03ActionPerformed

    private void button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button01ActionPerformed
        // TODO add your handling code here:
         if (jLabelPosicion.getText().length()<2) {
          jLabelPosicion.setText(jLabelPosicion.getText()+"1");
        }
        
    }//GEN-LAST:event_button01ActionPerformed

    private void button02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button02ActionPerformed
        // TODO add your handling code here:
        if (jLabelPosicion.getText().length()<2) {
          jLabelPosicion.setText(jLabelPosicion.getText()+"2");
        }
         
    }//GEN-LAST:event_button02ActionPerformed

    private void button05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button05ActionPerformed
        // TODO add your handling code here:
        if (jLabelPosicion.getText().length()<2) {
                    jLabelPosicion.setText(jLabelPosicion.getText()+"5");

        }
         
    }//GEN-LAST:event_button05ActionPerformed

    private void button00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button00ActionPerformed
        // TODO add your handling code here:
        if (jLabelPosicion.getText().length()<2) {
                           jLabelPosicion.setText(jLabelPosicion.getText()+"0");   

        }
      
    }//GEN-LAST:event_button00ActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        // TODO add your handling code here:
       jLabelPosicion.setText("");
    }//GEN-LAST:event_buttonBorrarActionPerformed

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
    try {
        // TODO add your handling code here://este es para pedir helados
        IceCream icecream;
        icecream = IM.getIceCreamFromMachine(jLabelPosicion.getText());
            if (icecream != null) {

                JOptionPane.showMessageDialog(rootPane, "Aquí tiene su " + icecream.getName() + " de tipo " + icecream.getType() , "Helado comprado!", HEIGHT);
               
                System.out.println("Total restante: " + df.format(IM.getPurse()) + "€");
                updatejLabelTextDinero();
                updateTablaHelados();
                jLabelPosicion.setText("");

            } 
                
            
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, "ERROR", "Helado comprado!", HEIGHT);
        Logger.getLogger(ExeGraph.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void button06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button06ActionPerformed
        // TODO add your handling code here:
        jLabelPosicion.setText(jLabelPosicion.getText()+"6");
    }//GEN-LAST:event_button06ActionPerformed

    private void Introducir_DineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Introducir_DineroActionPerformed
        // TODO add your handling code here:
        InsertMoneyJDialog insertMoney = new InsertMoneyJDialog(this,true);//Este true significa que es modal
        insertMoney.setVisible(true);
    }//GEN-LAST:event_Introducir_DineroActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        // TODO add your handling code here:
        SalesJDialog sales = new SalesJDialog(this,true);//Este true significa que es modal
        sales.setVisible(true);
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    try {
        // TODO add your handling code here:
        IM.refillIceCreams();
        updateTablaHelados();
    } catch (Exception ex) {
        Logger.getLogger(ExeGraph.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TablaHeladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaHeladosMouseClicked
        // TODO add your handling code here:
              DefaultTableModel m = (DefaultTableModel) this.TablaHelados.getModel();
String posicion;
        // Obtén el índice de la fila seleccionada
        int rowIndex = this.TablaHelados.rowAtPoint(evt.getPoint());

        // Asegúrate de que la fila está dentro del rango de la tabla
        if (rowIndex >= 0 && rowIndex < m.getRowCount()) {
            // Obtén el valor de la columna 1 (segunda columna, ya que el índice comienza en 0)
            Object pos = m.getValueAt(rowIndex, 0);
       posicion = pos.toString();
            // Aquí puedes agregar el código para trabajar con la posición obtenida
            this.jLabelPosicion.setText(posicion);
        }
    }//GEN-LAST:event_TablaHeladosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExeGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ExeGraph().setVisible(true);
            
            }

            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Introducir_Dinero;
    private javax.swing.JTable TablaHelados;
    private java.awt.Button button00;
    private java.awt.Button button01;
    private java.awt.Button button02;
    private java.awt.Button button03;
    private java.awt.Button button04;
    private java.awt.Button button05;
    private java.awt.Button button06;
    private java.awt.Button button07;
    private java.awt.Button button08;
    private java.awt.Button button09;
    private java.awt.Button buttonBorrar;
    private java.awt.Button buttonConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelElecion;
    private javax.swing.JLabel jLabelPosicion;
    private javax.swing.JLabel jLabelTextDinero;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
