/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.IM.gui;

import static com.IM.gui.ExeGraph.IM;

/**
 *
 * @author Jaime Riesgo
 */
public class InsertMoneyJDialog extends javax.swing.JDialog {

    /**
     * Creates new form InsertMoneyJDialog
     */
    public InsertMoneyJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (ExeGraph) parent;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button20cent = new java.awt.Button();
        button1euro = new java.awt.Button();
        button50cent = new java.awt.Button();
        button5cent = new java.awt.Button();
        button10cent = new java.awt.Button();
        button2euro = new java.awt.Button();
        jLabelTextDinero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        button20cent.setLabel("0.20");
        button20cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20centActionPerformed(evt);
            }
        });

        button1euro.setLabel("1");
        button1euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1euroActionPerformed(evt);
            }
        });

        button50cent.setLabel("0.50");
        button50cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button50centActionPerformed(evt);
            }
        });

        button5cent.setLabel("0.05");
        button5cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5centActionPerformed(evt);
            }
        });

        button10cent.setLabel("0.10");
        button10cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10centActionPerformed(evt);
            }
        });

        button2euro.setLabel("2");
        button2euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2euroActionPerformed(evt);
            }
        });

        jLabelTextDinero.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelTextDinero.setText("Dinero: "+IM.getPurse()+"€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextDinero)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button20cent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(button50cent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button1euro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(button2euro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button5cent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button10cent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelTextDinero)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button5cent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button10cent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button50cent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button20cent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1euro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2euro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button20centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20centActionPerformed
        // TODO add your handling code here:
       IM.setPurse(IM.getPurse()+0.20d);
       actualizarDisplay();
    }//GEN-LAST:event_button20centActionPerformed

    private void button1euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1euroActionPerformed
        // TODO add your handling code here:
        IM.setPurse(IM.getPurse()+1);
        actualizarDisplay();
        
    }//GEN-LAST:event_button1euroActionPerformed

    private void button50centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button50centActionPerformed
        // TODO add your handling code here:
        IM.setPurse(IM.getPurse()+0.50d);
        actualizarDisplay();
    }//GEN-LAST:event_button50centActionPerformed

    private void button5centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5centActionPerformed
        // TODO add your handling code here:
        IM.setPurse(IM.getPurse()+0.05d);
        actualizarDisplay();
    }//GEN-LAST:event_button5centActionPerformed

    private void button10centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10centActionPerformed
        // TODO add your handling code here:
        IM.setPurse(IM.getPurse()+0.10d);
        actualizarDisplay();
    }//GEN-LAST:event_button10centActionPerformed

    private void button2euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2euroActionPerformed
        // TODO add your handling code here:
        IM.setPurse(IM.getPurse()+2);
        actualizarDisplay();
    }//GEN-LAST:event_button2euroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertMoneyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertMoneyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertMoneyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertMoneyJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InsertMoneyJDialog dialog = new InsertMoneyJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public ExeGraph padre;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button10cent;
    private java.awt.Button button1euro;
    private java.awt.Button button20cent;
    private java.awt.Button button2euro;
    private java.awt.Button button50cent;
    private java.awt.Button button5cent;
    private javax.swing.JLabel jLabelTextDinero;
    // End of variables declaration//GEN-END:variables

    private void actualizarDisplay() {
        jLabelTextDinero.setText("Dinero: "+IM.getPurse()+"€");
        padre.updatejLabelTextDinero();
    }
}
